# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RAM_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(644, 480)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(30, -1, 30, 30)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setMaximumSize(QtCore.QSize(100, 100))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap("resources/emblema_Quetzal-1.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_3.addWidget(self.label_24)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setVerticalSpacing(6)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_12 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcdNumber)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_2)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_3)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_4)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_7)
        self.lcdNumber_10 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_10.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_10.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_10)
        self.lcdNumber_11 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_11.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_11.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_11)
        self.lcdNumber_12 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_12.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_12.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_12)
        self.lcdNumber_13 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_13.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_13.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_13)
        self.lcdNumber_14 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_14.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_14)
        self.lcdNumber_15 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_15.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_15)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_14 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.label_17 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.label_18 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.label_20 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.label_21 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_5)
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_6)
        self.lcdNumber_16 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_16.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_16)
        self.lcdNumber_17 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_17.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_17.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_17)
        self.lcdNumber_18 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_18.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_18.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_18)
        self.lcdNumber_19 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_19.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_19.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_19)
        self.lcdNumber_20 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_20.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_20.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_20)
        self.lcdNumber_21 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_21.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_21)
        self.lcdNumber_22 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_22.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_22.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_22)
        self.label_22 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_8)
        self.label_23 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.lcdNumber_9 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.lcdNumber_9)
        self.horizontalLayout.addLayout(self.formLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Parámetros de RAM"))
        self.label.setText(_translate("Dialog", "Guatemalan Nanosatellite :: Quetzal-1\n"
"RAM Parameters"))
        self.label_2.setText(_translate("Dialog", "CDHS Cycle Time:"))
        self.label_4.setText(_translate("Dialog", "CDHS Watchdog:"))
        self.label_5.setText(_translate("Dialog", "ADM SOC Limit:"))
        self.label_6.setText(_translate("Dialog", "ADM Cycle Time:"))
        self.label_7.setText(_translate("Dialog", "ADM Burn Time:"))
        self.label_8.setText(_translate("Dialog", "ADM Max Cycles:"))
        self.label_9.setText(_translate("Dialog", "ADM Wait Time 1:"))
        self.label_10.setText(_translate("Dialog", "ADM Wait Time 2:"))
        self.label_11.setText(_translate("Dialog", "ADM Enable:"))
        self.label_12.setText(_translate("Dialog", "ADCS SOC Limit:"))
        self.label_13.setText(_translate("Dialog", "HEATER Cycle Time:"))
        self.label_3.setText(_translate("Dialog", "COMMS SOC Limit:"))
        self.label_14.setText(_translate("Dialog", "COMMS Cycle Time:"))
        self.label_15.setText(_translate("Dialog", "PAYLOAD SOC Limit:"))
        self.label_16.setText(_translate("Dialog", "PAYLOAD Cycle Time:"))
        self.label_17.setText(_translate("Dialog", "PAYLOAD Op Mode:"))
        self.label_18.setText(_translate("Dialog", "PAYLOAD Enable:"))
        self.label_19.setText(_translate("Dialog", "CAM Resolution:"))
        self.label_20.setText(_translate("Dialog", "CAM Exposure:"))
        self.label_21.setText(_translate("Dialog", "CAM Save Time:"))
        self.label_22.setText(_translate("Dialog", "HEATER Emergency On Time:"))
        self.label_23.setText(_translate("Dialog", "HEATER Emergency Off Time:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
