# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RAM_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(759, 824)
        self.lcdNumber_21 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_21.setGeometry(QtCore.QRect(580, 520, 111, 41))
        self.lcdNumber_21.setNumDigits(5)
        self.lcdNumber_21.setObjectName("lcdNumber_21")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_12.setGeometry(QtCore.QRect(230, 370, 111, 41))
        self.lcdNumber_12.setNumDigits(5)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_20.setGeometry(QtCore.QRect(580, 470, 111, 41))
        self.lcdNumber_20.setNumDigits(5)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_8.setGeometry(QtCore.QRect(320, 670, 111, 41))
        self.lcdNumber_8.setNumDigits(5)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_22 = QtWidgets.QLabel(Dialog)
        self.label_22.setGeometry(QtCore.QRect(100, 520, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_22.setGeometry(QtCore.QRect(580, 370, 111, 41))
        self.lcdNumber_22.setNumDigits(5)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(60, 420, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_20 = QtWidgets.QLabel(Dialog)
        self.label_20.setGeometry(QtCore.QRect(70, 270, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_6.setGeometry(QtCore.QRect(580, 220, 111, 41))
        self.lcdNumber_6.setNumDigits(5)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label_16 = QtWidgets.QLabel(Dialog)
        self.label_16.setGeometry(QtCore.QRect(40, 620, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(270, 60, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_24 = QtWidgets.QLabel(Dialog)
        self.label_24.setGeometry(QtCore.QRect(390, 170, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(430, 570, 321, 251))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("emblema_Quetzal-1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_18.setGeometry(QtCore.QRect(580, 320, 111, 41))
        self.lcdNumber_18.setNumDigits(5)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.label_31 = QtWidgets.QLabel(Dialog)
        self.label_31.setGeometry(QtCore.QRect(60, 470, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_16.setGeometry(QtCore.QRect(580, 170, 111, 41))
        self.lcdNumber_16.setNumDigits(5)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_10.setGeometry(QtCore.QRect(230, 270, 111, 41))
        self.lcdNumber_10.setNumDigits(5)
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.label_27 = QtWidgets.QLabel(Dialog)
        self.label_27.setGeometry(QtCore.QRect(430, 470, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_19 = QtWidgets.QLabel(Dialog)
        self.label_19.setGeometry(QtCore.QRect(70, 320, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_30 = QtWidgets.QLabel(Dialog)
        self.label_30.setGeometry(QtCore.QRect(430, 520, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_19.setGeometry(QtCore.QRect(580, 420, 111, 41))
        self.lcdNumber_19.setNumDigits(5)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.label_32 = QtWidgets.QLabel(Dialog)
        self.label_32.setGeometry(QtCore.QRect(410, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_11.setGeometry(QtCore.QRect(230, 320, 111, 41))
        self.lcdNumber_11.setNumDigits(5)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_14.setGeometry(QtCore.QRect(230, 470, 111, 41))
        self.lcdNumber_14.setNumDigits(5)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(400, 120, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_17.setGeometry(QtCore.QRect(580, 270, 111, 41))
        self.lcdNumber_17.setNumDigits(5)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 10, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_23 = QtWidgets.QLabel(Dialog)
        self.label_23.setGeometry(QtCore.QRect(380, 270, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_18 = QtWidgets.QLabel(Dialog)
        self.label_18.setGeometry(QtCore.QRect(40, 670, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_25 = QtWidgets.QLabel(Dialog)
        self.label_25.setGeometry(QtCore.QRect(420, 420, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(40, 720, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_3.setGeometry(QtCore.QRect(230, 220, 111, 41))
        self.lcdNumber_3.setNumDigits(5)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_13.setGeometry(QtCore.QRect(230, 420, 111, 41))
        self.lcdNumber_13.setNumDigits(5)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_15.setGeometry(QtCore.QRect(230, 520, 111, 41))
        self.lcdNumber_15.setNumDigits(5)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.label_21 = QtWidgets.QLabel(Dialog)
        self.label_21.setGeometry(QtCore.QRect(70, 370, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(60, 120, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(80, 220, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_9.setGeometry(QtCore.QRect(320, 720, 111, 41))
        self.lcdNumber_9.setNumDigits(5)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_7.setGeometry(QtCore.QRect(230, 620, 111, 41))
        self.lcdNumber_7.setNumDigits(5)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_4.setGeometry(QtCore.QRect(230, 570, 111, 41))
        self.lcdNumber_4.setNumDigits(5)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_5.setGeometry(QtCore.QRect(580, 120, 111, 41))
        self.lcdNumber_5.setNumDigits(5)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(70, 570, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_26 = QtWidgets.QLabel(Dialog)
        self.label_26.setGeometry(QtCore.QRect(400, 320, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(230, 120, 111, 41))
        self.lcdNumber.setNumDigits(5)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(230, 170, 111, 41))
        self.lcdNumber_2.setNumDigits(5)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(390, 220, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        
    def update_LCD(self, beacon_data):
        self.lcdNumber.display(beacon_data[61])
        self.lcdNumber_2.display(beacon_data[62])
        self.lcdNumber_3.display(beacon_data[63])
        self.lcdNumber_4.display(beacon_data[64])
        self.lcdNumber_5.display(beacon_data[65])
        self.lcdNumber_6.display(beacon_data[66])
        self.lcdNumber_7.display(beacon_data[67])
        self.lcdNumber_8.display(beacon_data[68])
        self.lcdNumber_9.display(beacon_data[69])
        self.lcdNumber_10.display(beacon_data[70])
        self.lcdNumber_11.display(beacon_data[71])
        self.lcdNumber_12.display(beacon_data[72])
        self.lcdNumber_13.display(beacon_data[73])
        self.lcdNumber_14.display(beacon_data[74])
        self.lcdNumber_15.display(beacon_data[75])
        self.lcdNumber_16.display(beacon_data[76])
        self.lcdNumber_17.display(beacon_data[77])
        self.lcdNumber_18.display(beacon_data[78])
        self.lcdNumber_19.display(beacon_data[79])
        self.lcdNumber_20.display(beacon_data[80])
        self.lcdNumber_21.display(beacon_data[81])
        self.lcdNumber_22.display(beacon_data[82])

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_22.setText(_translate("Dialog", "ADM Enable:"))
        self.label_5.setText(_translate("Dialog", "CHDS Watchdog:"))
        self.label_29.setText(_translate("Dialog", "ADM Wait Time 1:"))
        self.label_20.setText(_translate("Dialog", "ADM Cycle Time:"))
        self.label_16.setText(_translate("Dialog", "HEATER Cycle Time:"))
        self.label_2.setText(_translate("Dialog", "RAM Parameters"))
        self.label_24.setText(_translate("Dialog", "COMMS Cycle Time:"))
        self.label_31.setText(_translate("Dialog", "ADM Wait Time 2:"))
        self.label_27.setText(_translate("Dialog", "CAM Exposure:"))
        self.label_19.setText(_translate("Dialog", "ADM Burn Time:"))
        self.label_30.setText(_translate("Dialog", "CAM Save Time:"))
        self.label_32.setText(_translate("Dialog", "PAYLOAD Enable:"))
        self.label_8.setText(_translate("Dialog", "COMMS SOC Limit:"))
        self.label.setText(_translate("Dialog", "Guatemalan Nanosatellite :: Quetzal-1"))
        self.label_23.setText(_translate("Dialog", "PAYLOAD Cycle Time:"))
        self.label_18.setText(_translate("Dialog", "HEATER Emergency On Time:"))
        self.label_25.setText(_translate("Dialog", "CAM Resolution:"))
        self.label_28.setText(_translate("Dialog", "HEATER Emergency Off Time:"))
        self.label_21.setText(_translate("Dialog", "ADM Max Cycles:"))
        self.label_4.setText(_translate("Dialog", "CDHS Cycle Time:"))
        self.label_6.setText(_translate("Dialog", "ADM SOC Limit:"))
        self.label_7.setText(_translate("Dialog", "ADCS SOC Limit:"))
        self.label_26.setText(_translate("Dialog", "PAYLOAD Op Mode:"))
        self.label_9.setText(_translate("Dialog", "PAYLOAD SOC Limit:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

